FROM nginx

LABEL Name="NGINX-APP"

LABEL Author="Kshitija"

COPY ngin-start.sh /usr/local/bin/ngin-start.sh

COPY index.html /usr/share/nginx/html/index.html

EXPOSE 8080

CMD [ "/usr/local/bin/ngin-start.sh" , "run" ]
